name: Version Resolver
author: sindre0830
description: Resolves the next version tag based on semantic versioning rules
branding:
  icon: package
  color: black

inputs:
  bump_type:
    description: The type of bump to perform (major, minor, patch)
    required: true
  prefix:
    description: The prefix to use for finding the current version
    default: ''
  postfix:
    description: The postfix to use for finding the current version
    default: ''
  current_version:
    description: The current version to bump

outputs:
  next_version:
    description: The next version without the prefix and postfix
  current_version:
    description: The current version without the prefix and postfix

runs:
  using: node20
  main: dist/index.js
