name: "Bug Report"
description: Report a bug or issue with the action.
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please provide a clear and concise description of the issue.
      placeholder: Briefly describe the problem you're experiencing...
    validations:
      required: true
  - type: input
    id: action-version
    attributes:
      label: "Action Version"
      description: Specify the version of the GitHub Action you are using (e.g., `v1.0.0`).
      placeholder: v1.0.0
    validations:
      required: true
  - type: dropdown
    id: context
    attributes:
      label: "Context of Issue"
      description: Select the context where the issue occurred.
      multiple: false
      options:
        - Pull Request
        - Push
        - Scheduled Workflow
        - Manually Triggered Workflow
        - Other
    validations:
      required: true
  - type: input
    id: runner-env
    attributes:
      label: "Runner Environment"
      description: Specify the runner environment (e.g., `ubuntu-latest`, `windows-latest`, `self-hosted`).
      placeholder: ubuntu-latest
    validations:
      required: true
  - type: textarea
    id: usage
    attributes:
      label: "Workflow Usage"
      description: Paste the relevant section of your workflow YAML file where the action is being used.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: Describe what you expected to happen.
      placeholder: The action should...
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: Describe what actually happened, including any error messages.
      placeholder: The action actually...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Provide relevant logs or error messages from the workflow run. This will be automatically formatted as code.
      render: bash
    validations:
      required: false
